### ISSUE TITLE
svelte-basic example doesn't work - error in commonjs - Cannot read property 'type' of null

### ISSUE THREAD

**Issue by panta** [alshdavid/crayon#37]
## Description

The `svelte-basic` example from the repo doesn't build/work, giving an error `[!] (plugin commonjs) TypeError: Cannot read property 'type' of null`

## To reproduce

```bash
$ git clone git@github.com:alshdavid/crayon.git
$ cd crayon/examples/svelte/svelte-basic
$ npm install
...
$ npm run dev
rollup v1.20.3
bundles src/main.js → public/bundle.js...
[!] (plugin commonjs) TypeError: Cannot read property 'type' of null
node_modules/crayon-svelte/dist/index.js
TypeError: Cannot read property 'type' of null
    at extractAssignedNames (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/rollup-pluginutils/dist/pluginutils.cjs.js:48:22)
    at Scope.options.params.forEach.param (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/rollup-pluginutils/dist/pluginutils.cjs.js:63:17)
    at Array.forEach (<anonymous>)
    at new Scope (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/rollup-pluginutils/dist/pluginutils.cjs.js:62:28)
    at Object.enter (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/rollup-pluginutils/dist/pluginutils.cjs.js:125:28)
    at visit (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/estree-walker/src/estree-walker.js:22:9)
    at visit (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/estree-walker/src/estree-walker.js:44:4)
    at visit (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/estree-walker/src/estree-walker.js:39:34)
    at visit (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/estree-walker/src/estree-walker.js:44:4)
    at visit (/private/tmp/crayon/examples/svelte/svelte-basic/node_modules/estree-walker/src/estree-walker.js:44:4)

1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crayon-svelte-example@1.0.0 autobuild: `rollup -c -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crayon-svelte-example@1.0.0 autobuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/panta/.npm/_logs/2019-08-30T09_04_35_033Z-debug.log
ERROR: "autobuild" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crayon-svelte-example@1.0.0 dev: `run-p start:dev autobuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crayon-svelte-example@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/panta/.npm/_logs/2019-08-30T09_04_35_094Z-debug.log
```

## Expected behavior
To get the development server running

## Desktop / environment
- macOS Mojave 10.14.6
- Crayon `master` (at 983fe37)

**Comment by srobertson421** [comment]
@panta Did you happen to find any workaround for this until there is a fix pushed in?

**Comment by alshdavid** [comment]
Just pushed an update that should address this. Please let me know if it's fixed for you and I'll close this ticket.
You'll need to update your `crayon` and `crayon-svelte` packages to the latest version in npm.

**Comment by srobertson421** [comment]
@alshdavid That fixed it for me, though I had to make sure to update crayon-animate and crayon-transition as well.

**Comment by alshdavid** [comment]
Awesome, I'll close this for now. Feel free to reopen if the issue persists
